plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.2'
	id 'io.spring.dependency-management' version '1.1.6'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {

	implementation "com.github.ben-manes.caffeine:caffeine:3.1.5"

	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

	implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0"                    // Swagger UI
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	implementation 'org.springframework:spring-messaging'
	implementation 'com.fasterxml.jackson.core:jackson-core'
	implementation 'com.fasterxml.jackson.core:jackson-databind'

	implementation 'org.springframework.boot:spring-boot-starter-amqp'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'


	implementation 'com.amazonaws:aws-java-sdk-s3:1.12.300' // 최신 버전으로 변경
	implementation 'com.amazonaws:aws-java-sdk-core:1.12.300' // 최신 버전으로 변경

	implementation 'org.hibernate:hibernate-spatial:6.0.0.Final' // Hibernate Spatial 업데이트
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

	implementation 'io.netty:netty-resolver-dns-native-macos:4.1.97.Final:osx-aarch_64'

	// reactor-netty 의존성 버전 내려보기
	implementation 'io.projectreactor.netty:reactor-netty:1.0.16'

	implementation 'com.auth0:java-jwt:4.2.1'

}

tasks.named('test') {
	useJUnitPlatform()
}
processResources.dependsOn('copySecret')

tasks.register('copySecret', Copy) {
	from './secure-submodule'
	include "application.yml"  // 복사할 파일들
	into 'src/main/resources'  // 복사 위치
}
tasks.withType(JavaCompile) {
	options.compilerArgs << "-parameters"
}